// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package protocol

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 数据原型
type Proto struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Op                   int32    `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Seq                  int32    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Compress             int32    `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	ContentType          int32    `protobuf:"varint,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Body                 []byte   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (m *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(m, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *Proto) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Proto) GetCompress() int32 {
	if m != nil {
		return m.Compress
	}
	return 0
}

func (m *Proto) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type RoomProto struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomProto) Reset()         { *m = RoomProto{} }
func (m *RoomProto) String() string { return proto.CompactTextString(m) }
func (*RoomProto) ProtoMessage()    {}
func (*RoomProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *RoomProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomProto.Unmarshal(m, b)
}
func (m *RoomProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomProto.Marshal(b, m, deterministic)
}
func (m *RoomProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomProto.Merge(m, src)
}
func (m *RoomProto) XXX_Size() int {
	return xxx_messageInfo_RoomProto.Size(m)
}
func (m *RoomProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomProto.DiscardUnknown(m)
}

var xxx_messageInfo_RoomProto proto.InternalMessageInfo

func (m *RoomProto) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomProto) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func init() {
	proto.RegisterType((*Proto)(nil), "meim.protocol.Proto")
	proto.RegisterType((*RoomProto)(nil), "meim.protocol.RoomProto")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xda, 0xc4, 0x74, 0x52, 0x11, 0x16, 0x29, 0xab, 0x08, 0x5b, 0x7a, 0x0a, 0x82,
	0x29, 0xea, 0x1b, 0xe4, 0xe6, 0x49, 0x19, 0x3c, 0x79, 0x4c, 0xba, 0xc6, 0x82, 0xdb, 0xd9, 0x26,
	0xa9, 0xd0, 0xb7, 0xf4, 0x09, 0xf6, 0x01, 0xf6, 0x29, 0x24, 0x13, 0xad, 0xed, 0xe5, 0xe7, 0xff,
	0xf6, 0x9f, 0x7f, 0x61, 0x06, 0x52, 0xdb, 0x50, 0x47, 0x39, 0xab, 0x38, 0x37, 0x7a, 0x6d, 0x06,
	0x5f, 0xd1, 0xe7, 0xf5, 0x5d, 0xbd, 0xee, 0x3e, 0x76, 0x65, 0x5e, 0x91, 0x59, 0xd6, 0x54, 0xd3,
	0x92, 0x93, 0x72, 0xf7, 0xce, 0xc4, 0xc0, 0x6e, 0x68, 0x2c, 0xbe, 0x03, 0x88, 0x5e, 0xf8, 0x9f,
	0x2b, 0x18, 0x7d, 0xe9, 0x46, 0x06, 0xf3, 0x20, 0x8b, 0x8a, 0x33, 0xef, 0x54, 0x8f, 0xd8, 0x8b,
	0x98, 0x41, 0x48, 0x56, 0x86, 0x9c, 0xc4, 0xde, 0xa9, 0x90, 0x2c, 0x86, 0x64, 0xfb, 0x4a, 0xab,
	0xb7, 0x72, 0xf4, 0x5f, 0x69, 0xf5, 0x16, 0x7b, 0x11, 0x19, 0x24, 0x15, 0x19, 0xdb, 0xe8, 0xb6,
	0x95, 0x63, 0xce, 0xa7, 0xde, 0xa9, 0xc3, 0x1b, 0x1e, 0x9c, 0xb8, 0x87, 0xb4, 0xa2, 0x4d, 0xa7,
	0x37, 0xdd, 0xeb, 0xde, 0x6a, 0x19, 0xf1, 0xf0, 0x85, 0x77, 0xea, 0xf8, 0x19, 0x8f, 0x41, 0xdc,
	0xc0, 0xb8, 0xa4, 0xd5, 0x5e, 0xc6, 0xf3, 0x20, 0x9b, 0x16, 0x89, 0x77, 0x8a, 0x19, 0x59, 0x17,
	0xcf, 0x30, 0x41, 0x22, 0x33, 0x6c, 0x35, 0x83, 0xb8, 0x21, 0x32, 0x4f, 0x2b, 0x5e, 0x6c, 0x82,
	0xbf, 0x24, 0x6e, 0x21, 0xe2, 0x03, 0xf0, 0x56, 0xe9, 0xc3, 0x65, 0x7e, 0x72, 0xc5, 0x9c, 0xcb,
	0x38, 0x8c, 0x14, 0xf0, 0x96, 0xfc, 0x05, 0x65, 0xcc, 0xee, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x0a, 0x68, 0xef, 0xcf, 0x83, 0x01, 0x00, 0x00,
}
